### ISSUE TITLE
No issue just 1.20.1 request

### ISSUE THREAD

**Issue by IsaDucko** [AyUpItsAli/TisButAScratch#1]
I also need the mod for my modpack, the red flashes just feel weird

**Comment by AyUpItsAli** [comment]
Sure thing. I'll update to cover all of 1.20 (Forge) while I'm at it as well.

**Comment by AyUpItsAli** [comment]
Mod now supports versions 1.18 to 1.20.4 https://modrinth.com/mod/tbas/version/1.0.0-1.20.1

FYI: If I update the mod again, I'll probably skip 1.20.5 and 1.20.6 and move straight to 1.21.

**Comment by IsaDucko** [comment]
tyty
